{{- include "itsm-mcp.validate" . }}
{{- if not .Values.itsm.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itsm-mcp.secretName" . }}
  labels:
    {{- include "itsm-mcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.itsm.auth.authtokenKey }}: {{ .Values.itsm.auth.authtoken | quote }}
{{- end }}
